### PR TITLE
[Documentation] Define "DSL"

### LINKED ISSUE #26: Documentation Enhancements
Feedback from @michsa:

- [ ] Document what a DSL is

### PR DESCRIPTION
**Pull request by daedalus28**
Fixes #26

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  You should add at least 1 more reviewer to the PR
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  Awesome! Thanks for the well-formatted PR!
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by michsa** [comment]
Beat me to it :(

**Comment by daedalus28** [comment]
It's probably not worth doing a release purely for a documentation change this trivial, so I'll hold on merging this PR for the moment.

**Comment by daedalus28** [comment]
Merging as this is harmless.

**Pull request merged**
